### ISSUE TITLE
tf.concat error on line 123 in clockwork_rnn.py 

### ISSUE THREAD

**Issue by GeloKing** [PanDav2/Clockwork-RNN#1]
Hi,
I'm new to tensorflow so I could be wrong, but when I run main.py, I got an error showing 

Traceback (most recent call last):
  File "C:/.../Clockwork-RNN-master/main.py", line 35, in <module>
    model = ClockworkRNN(config)
  File "C:\...\Clockwork-RNN-master\models\clockwork_rnn.py", line 47, in __init__
    self.create_model()
  File "C:\...\Clockwork-RNN-master\models\clockwork_rnn.py", line 123, in create_model
    **state = tf.concat(0, [partial_state, tf.slice(state, [active_rows, 0], [-1, -1])], name = 'new_state')**
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1043, in concat
    dtype=dtypes.int32).get_shape(
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 676, in convert_to_tensor
    as_ref=False)
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 741, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\framework\constant_op.py", line 113, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\framework\constant_op.py", line 102, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 374, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

I debug the code and find that the shape of 'state' variable is (36,1) and the code tries to slice it with begin = [ active_rows (=36) , 0 ]. Maybe the value is active_rows is incorrect? Or maybe I use a different version of tensorflow (my tf version is 1.2.1)?
Please let me know if you can confirm this error and what is the correct version of this line. Thanks a lot!
Regards,

**Comment by GeloKing** [comment]
Ok I know why. Tensorflow change concat format in the new version. I think I can close this issue. Thanks a lot.
